services:
  api-gateway:
#    image: tgkhanhdev/api-gateway:test-v1
    build:
      context: api-gateway # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    ports:
      - "8005:8080"
    restart: unless-stopped

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    volumes:
      - ${MUSICS_PATH}:/root/storage/musics/
      - ${IMAGES_PATH}:/root/storage/images/
    restart: unless-stopped
    env_file:
      - ./media-service/.env

  auth-service:
#    image: tgkhanhdev/auth-service:test-v1
    build:
      context: auth-service # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    restart: unless-stopped

  music-service:
#    image: tgkhanhdev/music-service:test-v1
    build:
      context: music-service # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    restart: unless-stopped