version: "3.3"

services:
  api-gateway:
#    image: tgkhanhdev/api-gateway:test-v1
    build:
      context: api-gateway # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    ports:
      - "8005:8080"
    restart: unless-stopped

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    volumes:
      - /mnt/media/spotify_app/musics/:/root/storage/musics/
      - /mnt/media/spotify_app/images/:/root/storage/images/
    restart: unless-stopped

  auth-service:
#    image: tgkhanhdev/auth-service:test-v1
    build:
      context: auth-service # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    restart: unless-stopped

  music-service:
#    image: tgkhanhdev/music-service:test-v1
    build:
      context: music-service # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
    restart: unless-stopped